image: docker:latest

services:
  - docker:dind

variables:
  AWS_ACCESS_KEY_ID: "AKIAZ2DIHJVJHCSTZNS7"
  AWS_SECRET_ACCESS_KEY: "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"
  TF_ROOT: ${CI_PROJECT_DIR}/terraform/dev
  PLAN: plan.cache
  PLAN_JSON: plan.json
  DOCKER_HOST: tcp://docker:2375


before_script:
  - apk add terraform
  - cd ${TF_ROOT}

stages:
  - prepare
  - validate
  - build
  - test
  - deploy

init:
  stage: prepare
  script:
    - apk update && apk add bash
    - apk add openrc
    - docker build --tag python-docker-app .

validate:
  stage: validate
  script:
    - terraform init
    - terraform validate

plan:
  stage: build
  script:
    - terraform init
    - terraform plan -out=$PLAN
    - terraform show --json $PLAN
  artifacts:
    reports:
      terraform: $PLAN_JSON

apply:
  stage: deploy
  script:
    - terraform init
    - terraform apply $PLAN
  dependencies:
    - plan
  when: manual
  only:
    - master