image: docker:latest

services:
  - docker:dind

variables:
  AWS_ACCESS_KEY_ID: "AKIAZ2DIHJVJHCSTZNS7"
  AWS_SECRET_ACCESS_KEY: "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"
  TF_ROOT: ${CI_PROJECT_DIR}/terraform/dev
  ECR_ROOT: ${CI_PROJECT_DIR}/terraform/modules/ecr
  PLAN: plan.cache
  PLAN_JSON: plan.json
  DOCKER_HOST: tcp://docker:2375


before_script:
  - apk add terraform

stages:
  - prepare
  - validate
  - build
  - test
  - deploy

init:
  stage: prepare
  script:
    - apk update && apk add bash
    - apk add openrc
    - cd $ECR_ROOT
    - terraform init
    - terraform plan
    - terraform apply -auto-approve

validate:
  stage: validate
  script:
    - cd ${TF_ROOT}
    - terraform init
    - terraform validate

plan:
  stage: build
  script:
    - cd ${TF_ROOT}
    - apk add aws-cli
    - terraform init
    - terraform plan -out=$PLAN
    - terraform show --json $PLAN
    - docker build --tag python-docker-app .
    - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 674528447826.dkr.ecr.eu-west-1.amazonaws.com
    - docker tag python-docker-app:latest 674528447826.dkr.ecr.eu-west-1.amazonaws.com/python-app-ecr:v1
    - docker push 674528447826.dkr.ecr.eu-west-1.amazonaws.com/python-app-ecr:v1
  artifacts:
    reports:
      terraform: $PLAN_JSON

apply:
  stage: deploy
  script:
    - cd ${TF_ROOT}
    - terraform init
    - terraform apply $PLAN
  dependencies:
    - plan
  when: manual
  only:
    - master