include:
  - template: Terraform.latest.gitlab-ci.yml

variables:
  AWS_ACCESS_KEY_ID: "AKIAZ2DIHJVJHCSTZNS7"
  AWS_SECRET_ACCESS_KEY: "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"
  TF_ROOT: ${CI_PROJECT_DIR}/terraform/dev
  PLAN: plan.cache
  PLAN_JSON: plan.json

before_script:
  - apk update
  - apk add docker openrc
  - addgroup username docker
  - rc-update add docker boot
  - service docker start
  - cd ${TF_ROOT}

stages:
  - prepare
  - validate
  - build
  - test
  - deploy

init:
  stage: prepare
  script:
    - terraform init
    - docker build --tag python-docker-app .

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: build
  script:
    - terraform plan -out=$PLAN
    - terraform show --json $PLAN
  artifacts:
    reports:
      terraform: $PLAN_JSON

apply:
  stage: deploy
  script:
    - terraform apply $PLAN
  dependencies:
    - plan
  when: manual
  only:
    - master