variable "vpc_cidr_block" {}
variable "name" {}
variable "public_cidr" {}
#variable "public_cidr_b" {}
variable "private_cidr" {}
#variable "private_cidr_b" {}
variable "eip_vpc" {}
variable "lb_sgname" {}
#variable "instance_sg" {}
variable "enable_dns" {}
variable "enable_support" {}
#variable "az_zone_a" {}
#variable "az_zone_b" {}