variable "ami" {}
variable "name" {}
variable "ec2_count" {}
variable "subnet_id" {}
variable "public_ip" {}
variable "instance_type" {}
variable "key_name" {}
variable "instance_sg" {}
variable "iam_role_name" {}
variable "profile_name" {}